kind: pipeline
name: default

workspace:
  base: /src
  path: drone_test

steps:
# - name: test
#   image: node
#   commands:
#     - echo install package
#     - npm ci
#     - echo install Chrome
#     - apt-get update -qq && apt-get install -qq --no-install-recommends chromium && apt-get clean && rm -rf /var/lib/apt/lists/* && ln -s /usr/bin/chromium /usr/bin/google-chrome
#     - echo test
#     - npm run test-ci
# - name: build
#   image: node
#   commands:
#     - echo build
#     - npm run build
# - name: docker
#   image: plugins/docker
#   settings:
#     repo: pzps94038/ron-web
#     username: pzps94038
#     password: 
#       from_secret: DOCKER_PWD
#     debug: true
#     tags:
#     - latest
#     - main
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: SCP_HOST
    username: 
      from_secret: SCP_USER
    password: 
      from_secret: SCP_PWD
    port: 22
    command_timeout: 2m
    script:
      - docker stop ron-web || true && \
        docker rm ron-web || true && \
        docker pull pzps94038/ron-web:latest && \
        docker run -d -p 83:80 --name ron-web --restart=always \
        -e PORT=80 \
        pzps94038/ron-web:latest
  # when:
  #   branch:
  #   - main
  #   event:
  #   - push
    
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
