kind: pipeline
name: default

steps:
  - name: check-chrome
    commands:
      - apt list --installed | grep google-chrome-stable
    when:
      status:
        - success
        - failure
  - name: install-chrome
    image: drone/drone-runner-exec
    commands:
      - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - apt-get update && apt-get install -yq google-chrome-stable
      - export CHROME_BIN=/usr/bin/google-chrome-stable
    when:
      status:
        - failure
  - name: set-chrome-env
    image: drone/drone-runner-exec
    commands:
      - export CHROME_BIN=/usr/bin/google-chrome-stable
    when:
      status:
        - success
  - name: test
    image: node
    commands:
      - npm ci
      - npm run test-ci
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
