kind: pipeline
name: unit-test

workspace:
  base: /src
  path: drone_test

steps:
- name: test
  image: node
  commands:
    - echo install package
    - npm ci
    - echo install Chrome
    - apt-get update -qq && apt-get install -qq --no-install-recommends chromium && apt-get clean && rm -rf /var/lib/apt/lists/* && ln -s /usr/bin/chromium /usr/bin/google-chrome
    - echo test
    - npm run test-ci
- name: build
  image: node
  commands:
    - echo build
    - npm run build
    
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
