kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
    - npm ci
- name: unit-test
  image: node
  commands:
    - npm run test-ci
    
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
