kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
    - npm ci
    - npm run test-ci
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
