kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
    - npm ci
    - apt-get update -qq \
    && apt-get install -qq --no-install-recommends \
      chromium \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/chromium /usr/bin/google-chrome
    - npm run test-ci
    
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
