kind: pipeline
name: default

steps:
- name: test
  environment:
    CHROME_BIN: /usr/bin/google-chrome-stable
  image: node
  commands:
  - apt-get update
  - apt-get -y install google-chrome-stable
  - npm ci
  - npm run test-ci
trigger:
  branch:
  - main
  - develop
  event:
  - push
  - pull_request
  - tag
