kind: pipeline
name: default

steps:
- name: test
  image: weboaks/node-karma-protractor-chrome:alpine-root
  commands:
    - npm ci
    - npm run test-ci
    
trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request
    - tag
