kind: pipeline
name: default

steps:
- name: test
  environment:
    CHROME_BIN: /usr/bin/google-chrome-stable
  image: node
  commands:
  - apt-get install -y wget
  - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - apt-get install ./google-chrome-stable_current_amd64.deb
  - npm ci
  - npm run test-ci
trigger:
  branch:
  - main
  - develop
  event:
  - push
  - pull_request
  - tag
