#%RAML 1.0
baseUri: http://localhost:3001/
title: SinoPac.Cawho.Api
version: 0.1

/api/misc/getMyHostInfo:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/MyHostInfo.json
