#%RAML 1.0
baseUri: http://localhost:3000/
title: RonWeb
version: 0.1
/api/article/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article/delete.json
/api/article:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article/create.json
/api/article/updateArticleViews/{id}:
  patch:
      uriParameters:
        id:
          description: The ID of the article
          type: number
      responses:
        200:
          body:
            application/json:
              example: !include examples/article/updateArticleViews.json
/api/articleCategory:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-category/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-category/create.json
/api/articleCategory/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-category
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-category/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-category/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-category/delete.json
/api/articleLabel:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-label/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-label/create.json
/api/articleLabel/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-label/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-label/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/article-label/delete.json
/api/login:
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/login/login.json
/api/refreshToken:
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/refresh-token/refreshToken.json
/api/contactUs:
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/contact-us/contactUs.json
/api/search/keyword/{keyword}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/search/keyword.json
/api/search/category/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/search/category.json
/api/search/label/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/search/label.json
/api/upload:
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/upload/upload.json
/api/adminArticle/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article/delete.json
/api/adminArticle:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article/create.json
/api/adminArticleCategory:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-category/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-category/create.json
/api/adminArticleCategory/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-category
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-category/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-category/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-category/delete.json
/api/adminArticleLabel:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-label/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-label/create.json
/api/adminArticleLabel/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-label/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-label/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article-label
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-article-label/delete.json
/api/adminCodeType:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code-type/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code-type/create.json
/api/adminCodeType/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-code-type
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code-type/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article-code-type
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code-type/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article-code-type
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code-type/delete.json
/api/adminCode:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code/get.json
  post:
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code/create.json
/api/adminCode/{id}:
  get:
    uriParameters:
      id:
        description: The ID of the article-code
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code/getId.json
  patch:
    uriParameters:
      id:
        description: The ID of the article-code
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code/patch.json
  delete:
    uriParameters:
      id:
        description: The ID of the article-code
        type: number
    responses:
      200:
        body:
          application/json:
            example: !include examples/admin-code/delete.json
