name: Node.js CI

on:
    pull_request:
        branches: ['main', 'develop']
    push:
        branches: ['main', 'develop']
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run prerender
            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: prerender
                  path: dist
                  retention-days: 1
            - run: npm run build
            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: csr
                  path: dist/RonWeb/browser
                  retention-days: 1
            - run: npm run build:sit:githubPage
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages
                folder: dist/RonWeb/browser
                token: ${{ secrets.TOKEN }}
