name: Node.js CI

on:
    pull_request:
        branches: ['main']
    push:
        branches: ['main']
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run prerender
            - name: Upload build artifact
              uses: actions/upload-artifact@v2
              with:
                  name: prerender
                  path: dist
                  retention-days: 1
            - run: npm run build:gitHubPage
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages
                folder: dist/RonWeb/browser
                token: ${{ secrets.TOKEN }}
            - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
              uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
              with:
                email: ${{ secrets.HEROKU_EMAIL }}
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                # Dockerfile directory.
                dockerfile_directory: ./
                # Dockerfile name.
                dockerfile_name: Dockerfile
                # (Optional, default: "")
                # Additional options of docker build command.
                docker_options: "--no-cache"
                # (Optional, default: "web")
                # Select the process type for which you want the docker container to be uploaded.
                # By default, this argument is set to "web".
                # For more information look at https://devcenter.heroku.com/articles/process-model
                process_type: web
