name: Node.js CI

on:
    pull_request:
        branches: ['main']
    push:
        branches: ['main']
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run prerender
            - name: Upload build artifact
              if: github.ref == 'refs/heads/main'
              uses: actions/upload-artifact@v2
              with:
                  name: prerender
                  path: dist
                  retention-days: 1
            - run: npm run build:gitHubPage
              if: github.ref == 'refs/heads/main'
            - name: Deploy to GitHub Pages
              if: github.ref == 'refs/heads/main'
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                branch: gh-pages
                folder: dist/RonWeb/browser
                token: ${{ secrets.TOKEN }}
            - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
              if: github.ref == 'refs/heads/main'
              uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
              with:
                email: ${{ secrets.HEROKU_EMAIL }}
                heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
            - name: Deploy to Heroku
              if: github.ref == 'refs/heads/main'
              run: |
                heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
                heroku stack:set container
                git push heroku main
